### ISSUE TITLE
Observables getting duplicate subscribers

### ISSUE THREAD

**Issue by jonahbron** [Reactive-Extensions/RxJS#651] opened 2015-04-03 21:29 UTC
In the example here:

http://codepen.io/jonahbron/pen/zxXQpM

A single-item array is turned into an Observable with `from`.  But as you can see from the `do` callback, zipping it against itself results in the `do` callback being called twice.  The correct behavior can be found in this example, which uses `just` instead.

http://codepen.io/jonahbron/pen/YPMbeP

**Comment by jonahbron** [comment] 2015-04-03 23:25
This may be part of a deeper problem.  Here's another example of two scenarios that you would expect to behave the same, but only one behaves properly.

http://codepen.io/jonahbron/pen/rabgRP?editors=001

**Comment by paulpdaniels** [comment] 2015-04-04 00:34
I think you are correct about there being a bug, but I think the intuition about which one is correct is flipped.  You *should* see two messages, since you are actually subscribing to the observable twice.

Each time you subscribe to an Observable it (should) create a new independent event stream. 

```javascript

var source = Rx.Observable.just(1).tap(function(x){ console.log(x);});

source.subscribe();
source.subscribe();

//Expected
//1
//1

//Actual
//1
```

The above is basically what you are doing (minus the selector and synchronization code that `.zip()` provides.

I think the problem is [here](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/do.js#L11). The observer is being created on '.do()' rather than inside of the `AnonymousObservable` meaning that when the first object completes the observer created by `do/tap` will never be called again.

**Comment by jonahbron** [comment] 2015-04-06 17:12
Okay.  What I'm wanting is to create a complicated tree of observables that are only processed once.  Do you know of an operator that can make an observable only emit once to all observables, instead of once to every subscription it gets?  Maybe this is a job for connectable observables?

**Comment by mattpodwysocki** [comment] 2015-04-06 17:19
@jonahbron I have fixed the inconsistency between the `just` and `of` implementations as @paulpdaniels  was correct about the bug.  What you're going to want to limit the side effects is to sure enough use a `ConnectableObservable` and in this case `publish().refCount()` or `share()` which does the same thing.  That will limit the side effects to only once for the entire session.

**Comment by jonahbron** [comment] 2015-04-06 17:23
That's awesome, thanks so much @mattpodwysocki.  I'll try to work on implementing that tomorrow.

**Comment by paulpdaniels** [comment] 2015-04-06 17:40
@mattpodwysocki I think it needs to be fixed [here](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/tap.js#L60) too. Though I don't know if perf/tap.js is currently part of the build.

**Comment by mattpodwysocki** [comment] 2015-04-06 18:59
@paulpdaniels it isn't but will fix anyways

**Comment by mattpodwysocki** [comment] 2015-04-06 20:39
Closing per fix

**Closed by mattpodwysocki** 2015-04-06 20:39 UTC

**Comment by jonahbron** [comment] 2015-04-07 19:07
@mattpodwysocki I changed all of the origin inputs to be Connectable with publish(), then waited to call `connect()` on them until after I subscribed.  It changed things, but now the processes are duplicated in parallel, instead of in series.  Before, the it would go through them all to one end, then again to another.  But now each step just happens twice at the same point.

I think this is because of the duplicate subscriptions from the same observable.  Is there an operator that can suppress duplicate subscribers?

**Comment by jonahbron** [comment] 2015-04-07 20:58
My network looks something like this:

       _
      |_|
       |
      / \
     _   _
    |_| |_|
     |   |
     _   _
    |_| |_|
     \   /
      \ /
       |
       _
      |_|

The last one is a `combineLatest`, and I subscribe to it once.  I want the top item to emit a value, the next two to accept that item and pass it along, the next ones accept the value too, then the last one (since it's a combining observable) accepts the previous two and emits a single combined value.  What I'm experiencing is that for every combination I make, the preceding observables are duplicated.

**Comment by paulpdaniels** [comment] 2015-04-07 21:15
`Publish` suppresses duplicates, but only to values earlier in the chain. Internally it creates a subject which subscribes to the observable after connect and then all of the observers subscribe to it rather than duplicating the stream.

I am guessing based on your description that you are doing something like this now:

```javascript

var source = Rx.Observable.just(1).publish();

var observable = source.tap(function(value){console.log(value);});

observable.subscribe();
observable.subscribe();

source.connect();

//Result
//1
//1

```
What you need is for the `publish()` to go *after* the tap.

**Comment by jonahbron** [comment] 2015-04-07 21:54
@paulpdaniels So in an unknown network (the network illustrated is just an example), is there a single point where I can place a connectable to prevent duplicates all up the chain?  Or if my network is unknown, should I make every single item in the network connectable?

**Comment by paulpdaniels** [comment] 2015-04-08 00:10
@jonahbron  I would not recommend making every item connectable, it will become a nightmare to manage their connected status. Short answer to your other question is no, every operator will "hide" the connectability of the previous operator. I would use the following rule of thumb for `publish()` (or any of the `multicast()` family): Place `publish()` as close to divergence points as possible, these are usually the points right before the semicolon in an operator chain.

For instance if I had the (extremely contrived but plausible) chain as follows:

```javascript

//Some observable
var source = getStockData();

var mappedSource = source
  .map(doSomeExpensiveMapping)
  .tap(logMyMappings)
  .share();

mappedSource.subscribe(logBackObserver);

var finalSource = mappedSource
  .filter(dateTimeFilter)
  .flatMap(doExpensiveFlatMapping)
  .distinctUntilChanged()
  .share();

finalSource.map(generateHTMLReport).subscribe(sendEmailObserver);
finalSource.map(convertToCSV).subscribe(writeDataStoreObserver);

```

In the above, `doSomeExpensiveMapping` and `logMyMappings` will execute three times for every message from source and `dateTimeFilter` and `doExpensiveFlatMapping` will occur twice for every message. Putting a `share()/publish()` in any one place would still result in double subscriptions and putting it after every operator is unmanageable.  Instead if you look at the points of divergence we see that we first diverge after `tap()` and again after 'distinctUntilChanged()', so we will eliminate the duplicates by placing `publish()` or (`share()` which is `publish().refCount()`) methods at these locations.

**Comment by jonahbron** [comment] 2015-04-15 16:42
@paulpdaniels Thanks again for your help. Adding `share()` at the split points eliminated the duplicate processes.  But it did introduce another interesting behavior.  I want to be able to subscribe to the terminal observable, accept items until it ends, then _re-subscribe_ to run the network of observables again.  When I try that, it simply does nothing the second time.  Does `refCount` support re-subscribing after it has un-subscribed?

**Comment by jonahbron** [comment] 2015-04-15 17:24
It looks like what I'm needing is `singleInstance`.  But it doesn't seem to be build in the distributable yet.  Trying to figure out how to get it.

**Comment by jonahbron** [comment] 2015-04-15 18:14
Hm, it seems that `singleInstance` doesn't behave as I expected.  Just like `replay`, it is sending down the same data again, instead of the new data as expected.

**Comment by jonahbron** [comment] 2015-04-15 18:41
Okay, `singleInstance` is putting me almost there.  However, it seems that `singleInstance` keeps the stream from ever completing.  Is that an expected behavior of a connectable?  Here's an example:

http://codepen.io/jonahbron/pen/yymqWR?editors=001

**Comment by jonahbron** [comment] 2015-04-15 18:56
I thought `singleInstance` was exactly what I needed, but it may not be.  It doesn't seem to allow re-subscribing after the stream has ended by itself.  Example:

http://codepen.io/jonahbron/pen/yymqWR?editors=001

**Comment by jonahbron** [comment] 2015-04-15 21:45
I'm seeing now that a connectable can't be used after it has ended.  Which makes sense.  Is there a way to make a connectable re-subscribe to its source and read from it again?

**Comment by jonahbron** [comment] 2015-04-16 18:42
Here is a clearer example of my use case.

http://codepen.io/jonahbron/pen/vEoore?editors=001

I don't even understand why it continues to evaluate observables after the terminal has emitted a single output, since all of the inputs only have one item.  The behavior of the second use is even stranger.  It emits values several times, each time incrementally changing.  This appears to be because combineLatest isn't clearing itself.

**Comment by urmastalimaa** [comment] 2015-04-16 19:50
I believe you are having problems because you are resubscribing to the same Observable in the `onComplete` callback which messes with operators which use `refCount`. 
If you restructure your observables so that you start with an Observable which emits different `data` and then you apply the transformations then you should have no problems.

**Comment by jonahbron** [comment] 2015-04-16 21:35
@urmastalimaa Hmm, that may be a possibility.  I was hoping to create a tree of observables that can be re-subscribed too, but simply pushing new values into it may be acceptable.  One issue is that it doesn't always emit one value.  Any ideas on how I could indicate that it's done emitting without actually completing?

What operators in my example are using refCount()?  I'm only using `from`, `flatMap`, `zip`, `combineLatest`, and `map`.

**Comment by urmastalimaa** [comment] 2015-04-17 05:45
@jonahbron 
Subscribing multiple times in itself isn't an problem, but resubscribing in an onComplete callback is not idiomatic and when doing so the various multicast (e.g share) operators don't to work as expected (especially when the data comes from cold observables as they come from the multiple `from` factories in your code).

If you can create a root Observable which emits *one piece of work* at a time (the emitted value itself can be an array or an Observable) then you should also be able use multicast operators in places where you want to limit side effects without issue.

**Comment by urmastalimaa** [comment] 2015-04-17 06:17
@jonahbron 
I modified your example a bit to illustrate my point: http://codepen.io/anon/pen/yNBNpJ?editors=001.

In this version the factors can arrive in any order, they are just grouped by process and then your original algorithm is applied. Note that there is also the `share` operator used which avoids duplicating side effects.

**Comment by jonahbron** [comment] 2015-04-17 18:24
@urmastalimaa Wow, thanks.  It'll take me a bit to work through your example and understand, but this may be what I need.  Thank you again for writing that up.

**Comment by urmastalimaa** [comment] 2015-04-17 20:10
No problem. You can email me if you need more help with your solution.

**Comment by jonahbron** [comment] 2015-04-23 18:28
@urmastalimaa Thanks again, I finally got a working solution based on your example.  Cheers :-)
