### ISSUE TITLE
Rx.Observable.fromCallback .publishLast().refCount() don't seem to be working

### ISSUE THREAD

**Issue by elayman** [Reactive-Extensions/RxJS#839] opened 2015-07-29 21:32 UTC
When you subscribe to fromCallback more than once, the code executes twice, which not only executes 'func' twice, it also does 'args.push(handler);' which modifies the already modified args array to look something like this:
args = 
1st subscriber: [data, data, handler]
2nd subscriber: [data, data, handler, handler] <-- Broken if your func expects (data, data, callback, boundData)

See JSBin for example:
http://jsbin.com/lifewehimu/1/edit?html,js,output

**Comment by paulpdaniels** [comment] 2015-07-29 22:04
Duplicate of #818. Should be fixed in the latest version (see #823).

**Comment by mattpodwysocki** [comment] 2015-08-17 21:44
@elayman fixed as per 3.0.1 and before

**Closed by mattpodwysocki** 2015-08-17 21:44 UTC
