### ISSUE TITLE
take(n) does not complete if observer triggers a new value while observing the last value

### ISSUE THREAD

**Issue by bman654** [Reactive-Extensions/RxJS#720] opened 2015-05-18 18:56 UTC
`q` in the following code will never see the completed notification:

```javascript
var s = new Rx.Subject();
var q = s.take(1);
q.subscribe(function (value) { s.onNext(value + 1); });
s.onNext(1);
```

See this jsFiddle: http://jsfiddle.net/bman654/4m17fke5/

**Comment by paulpdaniels** [comment] 2015-05-18 19:16
See these [lines](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/take.js#L22-L24).  The problem is that you are recursively calling onNext which means that at line 24 `r` is less than zero.  In general it is a bad idea to feed your streams from nested internal sources. That being said we should guard against this, so I will submit a patch for this.

**Comment by mattpodwysocki** [comment] 2015-05-22 11:37
@bman654 fixed with a simple <= check which will fix that but not disallow

**Closed by mattpodwysocki** 2015-05-22 11:37 UTC
