### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by lispking** [Reactive-Extensions/RxJS#816] opened 2015-07-16 09:57 UTC
Init web app will be display TypeError. The detail message:
```
db.inherits.da.internals.inherits @ rx.lite.compat.js:557
(anonymous function) @ rx.testing.js:362
(anonymous function) @ rx.testing.js:527
call.Observer @ rx.testing.js:32
(anonymous function) @ rx.testing.js:34
```

**Comment by paulpdaniels** [comment] 2015-07-16 19:37
Do you have some example of what you are doing?

**Comment by lispking** [comment] 2015-07-17 15:44
u can use newest version like demo: http://ymusica.herokuapp.com.

**Comment by lispking** [comment] 2015-07-17 15:49
now bower install default branch is:https://github.com/Reactive-Extensions/RxJS/blob/v.2.5.3/dist/rx.lite.compat.js#L557

**Comment by paulpdaniels** [comment] 2015-07-17 18:46
I'm not seeing any errors when running your application. It looks like in your example you are doing something with the testing library, perhaps post a sample that demonstrates that behavior?

**Comment by lispking** [comment] 2015-07-18 03:57
that example is not mine. i just use these demo and that will be demonstrates.

**Comment by lispking** [comment] 2015-07-18 16:41
i found these behavior is that include rx.testing.js, if use bower install rxjs --save, these command will be auto include <script src="bower_components/rxjs/dist/rx.testing.js"></script>.

**Comment by lispking** [comment] 2015-07-18 16:42
i found these behavior is that include rx.testing.js, if use bower install rxjs --save, these command will be auto include bower_components/rxjs/dist/rx.testing.js and another dist/***.js code.

**Comment by mattpodwysocki** [comment] 2015-09-22 05:07
Closing as I'm not able to reproduce here

**Closed by mattpodwysocki** 2015-09-22 05:07 UTC
