### ISSUE TITLE
CombineLatest is sharing value

### ISSUE THREAD

**Issue by salper** [Reactive-Extensions/RxJS#964] opened 2015-10-13 11:02 UTC
It seems that `combineLatest` behaviour has changed since v4:
```javascript
import Rx from 'rx';

const action1$ = new Rx.Subject();
const action2$ = new Rx.Subject();
const source$ = action1$.combineLatest(action2$, (...args) => args);

const sub1$ = source$.subscribe(console.log.bind(console, 'sub1'));

action1$.onNext('foo');
action2$.onNext('bar');

sub1$.dispose();

source$.subscribe(console.log.bind(console, 'sub2'));

action1$.onNext('baz');
// Rx < v4 => nothing happens, which is expected as action2$ subscription
// in combineLatest should not be shared (not intentionally at least)
// Rx >= 4 => [ 'baz', 'bar' ]; even so the sub1$ is disposed, action2$ 
// is still shared (or memoized)
```

I did not check the code yet as I don't know if this is the new intended behaviour. But it's strange, as sharing subscriptions has always been explicit (it's trigger feast now in our data graph).

**Comment by mattpodwysocki** [comment] 2015-10-13 17:14
@salper yes, it was a regression and has since been fixed and has been fixed with 4.0.3

**Closed by mattpodwysocki** 2015-10-13 17:14 UTC
