### ISSUE TITLE
zip bug introduced that results in values being consumed

### ISSUE THREAD

**Issue by dwsmorris** [Reactive-Extensions/RxJS#590] opened 2015-02-18 10:27 UTC
var integers = Rx.Observable.from([0, 1, 2, 3]);
  var resultStream = integers.zip(integers, function (a, b) {
   return [a, b];
  }).subscribe(function (pair) {
   console.log(pair[0] + ":" + pair[1])
  });

output at 2.3.14:
0:0
1:1
2:2
3:3
I think this is correct.

output at current head:
0:1
2:3
…

----------------------------------

I was actually performing something like the following:

  var resultStream = integers.zip(integers.map(function (value) { return value * value; }), function (a, b) {
   return [a, b];
  }).subscribe(function (pair) {
   console.log(pair[0] + ":" + pair[1])
  });

which now yields:
0:1
2:9

instead of the expected:
0:0
1:1
2:4
3:9
as it did back at v2.3.14

**Comment by mattpodwysocki** [comment] 2015-02-18 17:19
@dwsmorris using the current head now, I get the following, so I cannot reproduce...  What browser/runtime are you using?

```js
var Rx = require('rx');

var integers = Rx.Observable.from([0, 1, 2, 3]);
var resultStream = integers.zip(integers, function (a, b) {
  return [a, b];
}).subscribe(function (pair) {
  console.log(pair[0] + ":" + pair[1])
});

/*
λ node ..\foo.js
0:0
1:1
2:2
3:3
*/
```

**Comment by mattpodwysocki** [comment] 2015-02-24 20:10
@dwsmorris can you clarify what runtime you are using that gives this behavior?  Like I said, I cannot reproduce here.

**Comment by dwsmorris** [comment] 2015-02-24 23:07
sorry - I haven't had time to come back to this.
runtime was in browser (ie11 through visual studio)
the error manifest at the revision where bug #587 was logged - I have not checked whether subsequent changes in the source have fixed the issue
if you cannot reproduce at v2.3.16 let me know and I will dig up more info
 
Date: Tue, 24 Feb 2015 12:11:06 -0800

**Comment by mattpodwysocki** [comment] 2015-03-18 17:24
@dwsmorris closing as it seems to be a dead issue here

**Closed by mattpodwysocki** 2015-03-18 17:24 UTC
