### ISSUE TITLE
BehaviorSubject and combineLatest

### ISSUE THREAD

**Issue by TimBeyer** [Reactive-Extensions/RxJS#769] opened 2015-06-16 13:18 UTC
We're trying to use Rx to spread data (models, collections etc) to our views and other components.

We're currently using Backbone for models, but want to switch to something immutable eventually, which is why we basically pretend that the models are immutable data that gets sent to the interested parts of the application when the core business logic changes things.

Since we're following a "re-render everything" approach, `BehaviorSubject` seemed to be the perfect class to allow us to have a current state that we can query when we render and that gets automatically updated, but that would also allow us to build more reactive patterns on top. That way we could also use this server-side when we render static HTML and have all data have an initial state, so that we can simply do an initial render using `Rx.BehaviorSubject.prototype.getValue()`.

Here's some example code

```javascript

var streamifyBackboneModel = function (model) {
    var stream = new Rx.BehaviorSubject(model);
    var changes = Rx.Observable.fromEvent(model, 'change');

    changes.map(function () {
        return model;
    }).subscribe(stream);

    return stream;
};

var orderStream = streamifyBackboneModel(order);
var restaurantStream = streamifyBackboneModel(restaurant);

var cartStream = Rx.Observable.combineLatest(orderStream, restaurantStream, function (order, restaurant) {
   return CartService.toCart(order, restaurant);
});

cartStream.subscribe(function (cart) {
    console.log('Got new cart', cart);
});
```

This all works well, but the problem is that once we use `combineLatest` there's no more `getValue()` function and we can no longer have a current state. 
With `bacon` this could be done with properties, but in Rx there is nothing like it. I also don't want to turn everything into a `BehaviorSubject` manually.

I'm wondering if I am using a wrong pattern and should solve the problem of having an initial state on the server in a different way, not propagating the state to the views via Observables.

Any idea how to best solve this?

**Comment by TimBeyer** [comment] 2015-06-16 14:50
I wrote a function that will combine multiple instances of `BehaviorSubject` into a new `BehaviorSubject`, but I am still not sure it's a good idea:

```javascript
var combineToBehaviorSubject = function (/* behaviorSubjects, combineFn */) {
    // combineFn is used to provide initial value
    var behaviorSubjects = _.initial(arguments);
    var combineFn = _.last(arguments);

    var initialValues = _.map(behaviorSubjects, function (subject) {
        return subject.getValue();
    });

    var initialValue = combineFn.apply(this, initialValues);
    var subject = new Rx.BehaviorSubject(initialValue);

    var stream = Rx.Observable.combineLatest.apply(Rx.Observable, arguments);
    stream.subscribe(subject);

    return subject;
};
```

**Comment by paulpdaniels** [comment] 2015-06-22 17:26
@TimBeyer I don't see why you need to use `getValue` you would get current state whenever you subscribed to the chain.

**Comment by TimBeyer** [comment] 2015-06-22 17:50
@paulpdaniels Maybe I haven't understood the difference between hot and cold observables correctly, but I want multiple subscribers to first asynchronously get the initial state, but then together get the most recent updates to all of them.

I also don't want to save the current state locally in the views every time a new value is emitted but be able to get all model states when `render` is called, which should be idempotent. When parent views call `render` their child views are rendered as well, so at the render call they need to know the current state of their observables even if they haven't changed.

What am I missing here?

**Comment by roganov** [comment] 2015-07-09 08:11
I've just ran into this issue. `combineLatest` of hot observables (`BehaviorSubject`s in my case) seem to produce a cold observable, which is confusing IMO.

**Comment by mattpodwysocki** [comment] 2015-07-09 22:23
@roganov yes, when going from a `BehaviorSubject` to `Observable` via `combineLatest` will produce a cold observable. Is that not a desired effect here?

**Comment by mattpodwysocki** [comment] 2015-07-09 22:24
@TimBeyer instead of `combineLatest` do you want `withLatestFrom`?

**Comment by roganov** [comment] 2015-07-10 10:31
@mattpodwysocki
I'm sorry, I'm a novice at Rx and still struggling with the concepts of Hot and Cold observables, so I was thinking  that my issue (a stream, returned by combineLatest, produced no value upon subscription) was caused by the fact that combineLatest produces a cold observable, but apparently I was wrong, since the issue got resolved somehow.

**Comment by mattpodwysocki** [comment] 2015-07-20 22:13
@roganov @TimBeyer ok, closing this issue as it seems there is no more traffic here

**Closed by mattpodwysocki** 2015-07-20 22:13 UTC

**Comment by EdmondChuiHW** [comment] 2018-03-03 00:41
I fail to find any documents on `combineLatest` producing a cold Observable, I thought it does the reverse and wasted time trying to wrap all array of Observables into `combinelatest`.  Does anyone know where this behaviour is implied/documented? Thanks

**Comment by paulpdaniels** [comment] 2018-03-03 13:42
@chuihinwai cold behavior is basically the default, since `Observables` generally strive to be lazy in their execution. You generally should look for documentation specifying the *opposite* behavior.

**Comment by EdmondChuiHW** [comment] 2018-03-04 07:47
@paulpdaniels Thanks for the note. In the process of converting all Promises to Observables in an Angular project. Awesome progress so far! All the transform/combine methods make the code way easier to follow. Keep up the great work!🤗
