### ISSUE TITLE
Equivalent to Bacon.combineTemplate()

### ISSUE THREAD

**Issue by zcregan** [Reactive-Extensions/RxJS#831] opened 2015-07-24 12:09 UTC
The feature I miss the most from Bacon: https://baconjs.github.io/api.html#bacon-combinetemplate

It's similar to Rx.Observable.combineLatest() except for two useful features:
1. It can also combine constant values (ie. not Rx.Observables). This is super useful if you're writing a library to be used in other projects where the library is passed in some configuration data. CombineTemplate makes it very easy and clean to accept direct values, or optionally observables that the library can respond to dynamically.
2. You supply an object template that defines the output element structure. You don't have to construct an output using the `resultSelector` function argument.

**Comment by plemarquand** [comment] 2015-07-24 13:50
Possible duplicate of #731. I was just googling around to find an equivalent in RxJS, found that PR, and then this one.

**Comment by paulpdaniels** [comment] 2015-07-24 20:26
I believe there was another library that already implemented. @xgrommx I think you found the link for it.

**Comment by mattpodwysocki** [comment] 2015-07-24 20:33
@zcregan closing as duplicate

**Closed by mattpodwysocki** 2015-07-24 20:33 UTC
